name: Deploy to Kubernetes

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Checkout the code from GitHub repository
      - name: Checkout code
        uses: actions/checkout@v2
      #Login to Docker Hub
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}  

      # Build Docker image and push it to Docker Hub
      - name: Build and push Docker image
        run: |
          docker build -t ${secrets.DOCKER_USERNAME}/my-app:latest -f argocd-cicd-setup/Dockerfile .
          docker push ${secrets.DOCKER_USERNAME}/my-app:latest
          
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.G_TOKEN }}

       - name: tag and push image to GHCR
       env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          GITHUB_REPOSITORY: ${{ github.repository }}
       run: |
         IMAGE_ID=ghcr.io/${GITHUB_REPOSITORY}/my-app:latest
         docker tag $DOCKER_USERNAME/my-app:latest $IMAGE_ID
         docker push $IMAGE_ID
